FROM node:latest

# создание директории приложения
WORKDIR /usr/src/users-system

# установка зависимостей
# символ астериск ("*") используется для того чтобы по возможности 
# скопировать оба файла: package.json и package-lock.json
COPY package*.json ./

RUN npm install
# Если вы создаете сборку для продакшн
# RUN npm ci --only=production

# копируем исходный код
COPY . .

EXPOSE 3333
# CMD [ "node", "ace", "serve", "--watch" ]